### ISSUE TITLE
Theme submission warning 

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/event-listing#19]
Results of Automated Theme Scanning: Pass
WARNING: screenshot.jpg is 575.6 KB in size. Large file sizes have a negative impact on website performance and loading time. Compress images before using them.
RECOMMENDED: No reference to register_block_style was found in the theme. Theme authors are encouraged to implement new block styles as a transition to block themes.
RECOMMENDED: No reference to register_block_pattern was found in the theme. Theme authors are encouraged to implement custom block patterns as a transition to block themes.
RECOMMENDED: No reference to add_theme_support( “align-wide” ) was found in the theme. It is recommended that the theme implement this functionality.
RECOMMENDED: No reference to add_editor_style() was found in the theme. It is recommended that the theme implement editor styling, so as to make the editor content match the resulting post output in the theme, for a better user experience.
RECOMMENDED: Tested up to is recommended to have major versions only (e.g. 5.8). Patch version is not needed (e.g. 5.8.1).
INFO: Possible hard-coded links were found in the file footer.php. 
Line 112: printf(esc_html__(‘%1$s %2$s.’, ‘event-listing’), ‘’, ’<a href=‘https://wp-eventmanager.com/'>WP Event Manager</a>‘);
INFO: Only one text-domain is being used in this theme. Make sure it matches the theme’s slug correctly so that the theme will be compatible with WordPress.org language packs. The domain found is event-listing.
INFO: WP_Filesystem was found in the file inc/functions/tgm-library.php. Theme Check is not able to determine if WP_Filesystem is used correctly. WP_Filesystem should only be used for theme upgrade operations, not for all file operations. Before continuing, you must manually review the code. Consider using file_get_contents(), scandir(), or glob(). It is not recommended to make changes to third-party frameworks that use WP_Filesystem, for example, TGMPA. 
Line 692: * Uses WP_Filesystem to process and handle the plugin installation
Line 697: * @uses WP_Filesystem
Line 728: // Pass necessary information via URL if WP_Filesystem is needed.
Line 741: $method = ‘’; // Leave blank so WP_Filesystem can populate it as necessary.
Line 747: if ( ! WP_Filesystem( $creds ) ) {
Line 748: request_filesystem_credentials( esc_url_raw( $url ), $method, true, false, array() ); // Setup WP_Filesystem.
Line 897: wp_filesystem’] ) ) {
Line 902: wp_filesystem’]->dirlist( $remote_source ) );
Line 903: wp_filesystem’]->is_dir( $source ) ) {
Line 931: wp_filesystem’]->move( $from_path, $to_path ) ) {
Line 2737: * through if a user has to use WP_Filesystem to enter their credentials.
Line 2810: // Pass all necessary information if WP_Filesystem is needed.
Line 2819: $method = ‘’; // Leave blank so WP_Filesystem can populate it as necessary.
Line 2820: $fields = array_keys( $_POST ); // Extra fields to pass to WP_Filesystem.
Line 2826: // Now we have some credentials, setup WP_Filesystem.
Line 2827: if ( ! WP_Filesystem( $creds ) ) {
Note: While the automated theme scan is based on the Theme Review Guidelines, it is not a complete review. A successful result from the scan does not guarantee that the theme will pass review. All submitted themes are reviewed manually before approval.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
Theme image size is Compress.
So I closed the issue.
