### ISSUE TITLE
Homepage button's tool-tip on 404 page is not translatable

### ISSUE THREAD

**Issue by Gozke** [wpeventmanager/event-listing#20]
**Problem**
Every string in the _404.php_ file is translatable, except for the tool-tip of the "Homepage" button. That's hard coded and says "Goto Home".
See https://github.com/wpeventmanager/event-listing/blob/bd29a70f873717644a454155768232bed195fec2/404.php#L16

**Impact**
Users cannot completely translate the theme without having to create a child theme.

**Comment by Gozke** [comment]
Hi There,

My client's purchased the wp-event-manager plugin along with a couple of great addon-s. So far we love the plugin and the this light weight theme. Thanks for the great job! ;)

My **first question** would be: Am I correct to assume that the theme development takes place in this repo?
If so, then I have a **followup question**: May I go ahead and create a PR to fix this issue?
(I have addressed the problem on my client's WP installation, but it would be great if I could get rid of the child-theme with the new version of the theme)

**Comment by kaushikpokal** [comment]
Remove hard coded content "Goto Home"  in the 404.php file.
