### ISSUE TITLE
Theme Layout

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/event-listing#21]
Layout : -

**Comment by kaushikpokal** [comment]
**Theme 1**
Online Education
[Online school.zip](https://github.com/wpeventmanager/event-listing/files/9335321/Online.school.zip)

**Comment by kaushikpokal** [comment]
**Theme2**
Yogasan
[Yogasan.zip](https://github.com/wpeventmanager/event-listing/files/9356644/Yogasan.zip)

**Comment by kaushikpokal** [comment]
**Theme3**
The Rock - DJ Theme
[The Rock.zip](https://github.com/wpeventmanager/event-listing/files/9393444/The.Rock.zip)

**Comment by kprav33n97** [comment]
Theme 1
Online Education

[event-listing-child-online-education.zip](https://github.com/wpeventmanager/event-listing/files/9432370/event-listing-child-online-education.zip)

**Comment by kaushikpokal** [comment]
https://github.com/wpeventmanager/wpem-themes/issues/1

Duplicate bug
