### ISSUE TITLE
Show wpm installation notice to install it directly

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/event-listing#7]
- Easily user can install wp event manager by just clicking the admin notice.

- Write text like event listing theme is much better with wpem

**Comment by ashokdudhat** [comment]
I think that it already done ?


<img width="1440" alt="Screenshot 2020-07-08 at 23 32 43" src="https://user-images.githubusercontent.com/15089059/86972524-61892880-c173-11ea-90de-2017a1681e79.png">

<img width="1437" alt="Screenshot 2020-07-08 at 23 33 50" src="https://user-images.githubusercontent.com/15089059/86972607-7fef2400-c173-11ea-80cc-c64156ad77f2.png">
